package com.example.data.remote

import android.content.Context
import android.content.SharedPreferences
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import java.util.concurrent.TimeUnit

class SupabaseClientManager(private val context: Context) {

  private val prefs: SharedPreferences =
    context.getSharedPreferences("supabase_config", Context.MODE_PRIVATE)

  companion object {
    const val DEFAULT_SUPABASE_URL = "https://lnrmwsiwuzminvazdvup.supabase.co"
    const val DEFAULT_SUPABASE_KEY =
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxucm13c2l3dXptaW52YXpkdnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1MTcwNzgsImV4cCI6MjEwNjA5MzA3OH0.0RQJiR8vGB9QFwmsJoo8aVsPqFeH0dWZDJEYYMsSTqI"

    const val SQL_SCHEMA_SCRIPT = """
-- =============================================
-- SAHABATSEKOLAH DATABASE SCHEMA UNTUK SUPABASE
-- Salin dan jalankan kode ini di: Supabase Dashboard -> SQL Editor
-- =============================================

-- 1. Tabel Siswa (students)
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    grade_class TEXT NOT NULL,
    student_number TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    avatar_color_hex TEXT NOT NULL DEFAULT '#FF8A80',
    target_savings BIGINT NOT NULL DEFAULT 250000,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Tabel Pemberitahuan Jam Pulang (dismissal_alerts)
CREATE TABLE IF NOT EXISTS public.dismissal_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_class TEXT NOT NULL,
    is_dismissed BOOLEAN NOT NULL DEFAULT true,
    dismissal_time TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    announced_by TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Tabel Antrean Penjemputan (pickup_queues)
CREATE TABLE IF NOT EXISTS public.pickup_queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    gate_location TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'MENUNGGU',
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Tabel Laporan Akademik (academic_reports)
CREATE TABLE IF NOT EXISTS public.academic_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    subject TEXT NOT NULL,
    score INT NOT NULL,
    category TEXT NOT NULL,
    teacher_feedback TEXT NOT NULL,
    badge TEXT NOT NULL,
    date TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Tabel Tabungan Siswa (saving_transactions)
CREATE TABLE IF NOT EXISTS public.saving_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    type TEXT NOT NULL, -- 'MASUK' atau 'KELUAR'
    note TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    formatted_date TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Tabel Absensi Harian (attendance_records)
CREATE TABLE IF NOT EXISTS public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    student_name TEXT NOT NULL,
    date TEXT NOT NULL,
    status TEXT NOT NULL, -- 'HADIR', 'SAKIT', 'IZIN'
    time TEXT NOT NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Tabel Galeri Kegiatan (school_activities)
CREATE TABLE IF NOT EXISTS public.school_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    date TEXT NOT NULL,
    description TEXT NOT NULL,
    likes INT NOT NULL DEFAULT 10,
    photo_type TEXT NOT NULL DEFAULT 'hero_banner',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Tabel Pesan Chat (chat_messages)
CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_role TEXT NOT NULL, -- 'ORANG_TUA' atau 'GURU'
    sender_name TEXT NOT NULL,
    text TEXT NOT NULL,
    time TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 9. Tabel Jadwal Ujian (exam_schedules)
CREATE TABLE IF NOT EXISTS public.exam_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL,
    exam_date TEXT NOT NULL,
    time_range TEXT NOT NULL,
    room TEXT NOT NULL,
    syllabus_summary TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Aktifkan Row Level Security (RLS) & Kebijakan Publik (Bisa dibaca & ditulis oleh Anon Key)
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access students" ON public.students FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.dismissal_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access dismissal_alerts" ON public.dismissal_alerts FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.pickup_queues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access pickup_queues" ON public.pickup_queues FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.academic_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access academic_reports" ON public.academic_reports FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.saving_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access saving_transactions" ON public.saving_transactions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access attendance_records" ON public.attendance_records FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.school_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access school_activities" ON public.school_activities FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access chat_messages" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.exam_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public anon access exam_schedules" ON public.exam_schedules FOR ALL USING (true) WITH CHECK (true);
"""
  }

  var supabaseUrl: String
    get() = prefs.getString("url", DEFAULT_SUPABASE_URL) ?: DEFAULT_SUPABASE_URL
    set(value) = prefs.edit().putString("url", value.trim()).apply()

  var supabaseAnonKey: String
    get() = prefs.getString("anon_key", DEFAULT_SUPABASE_KEY) ?: DEFAULT_SUPABASE_KEY
    set(value) = prefs.edit().putString("anon_key", value.trim()).apply()

  val isConfigured: Boolean
    get() = supabaseUrl.isNotBlank() && supabaseAnonKey.isNotBlank()

  private var cachedApi: SupabaseApi? = null
  private var lastUrl: String = ""
  private var lastKey: String = ""

  fun getApi(): SupabaseApi? {
    if (!isConfigured) return null

    val currentUrl = supabaseUrl
    val currentKey = supabaseAnonKey

    if (cachedApi != null && currentUrl == lastUrl && currentKey == lastKey) {
      return cachedApi
    }

    var cleanUrl = currentUrl.trim().removeSuffix("/")
    val baseUrl = if (cleanUrl.endsWith("/rest/v1")) {
      "$cleanUrl/"
    } else {
      "$cleanUrl/rest/v1/"
    }

    val authInterceptor = Interceptor { chain ->
      val original = chain.request()
      val request = original.newBuilder()
        .header("apikey", currentKey)
        .header("Authorization", "Bearer $currentKey")
        .header("Content-Type", "application/json")
        .method(original.method, original.body)
        .build()
      chain.proceed(request)
    }

    val logging = HttpLoggingInterceptor().apply {
      level = HttpLoggingInterceptor.Level.BASIC
    }

    val okHttpClient = OkHttpClient.Builder()
      .addInterceptor(authInterceptor)
      .addInterceptor(logging)
      .connectTimeout(15, TimeUnit.SECONDS)
      .readTimeout(15, TimeUnit.SECONDS)
      .build()

    val moshi = Moshi.Builder()
      .add(KotlinJsonAdapterFactory())
      .build()

    val retrofit = Retrofit.Builder()
      .baseUrl(baseUrl)
      .client(okHttpClient)
      .addConverterFactory(MoshiConverterFactory.create(moshi))
      .build()

    val api = retrofit.create(SupabaseApi::class.java)
    cachedApi = api
    lastUrl = currentUrl
    lastKey = currentKey
    return api
  }

  suspend fun testConnection(): Result<String> {
    val api = getApi() ?: return Result.failure(Exception("URL Supabase atau Anon Key belum diisi!"))
    return try {
      val response = api.getStudents()
      if (response.isSuccessful) {
        val count = response.body()?.size ?: 0
        Result.success("Koneksi Supabase Sukses! Berhasil terhubung (Data siswa: $count)")
      } else {
        Result.failure(Exception("Koneksi gagal HTTP ${response.code()}: ${response.message()}"))
      }
    } catch (e: Exception) {
      Result.failure(Exception("Gagal menghubungi server Supabase: ${e.localizedMessage}"))
    }
  }
}
